### ISSUE TITLE
CI/CD: Package Tests job should follow CI

### ISSUE THREAD

**Issue by adambonsu** [adambonsu/GreetingHexJavascriptReact#6]
```
name: CI-CD
run-name: "CI-CD run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_dispatch:
concurrency:
    group: ci-cd ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    ci:
        permissions:
          contents: read
          packages: write
        secrets: inherit
        uses: ./.github/workflows/ci.yml
    package-tests:
        permissions:
          contents: read
          packages: write
        secrets: inherit
        uses: ./.github/workflows/package-tests.yml
        needs: ci
    cd:
        permissions:
            contents: read
        secrets: inherit
        uses: ./.github/workflows/cd.yml
        needs: package-tests
```
